# Generated by Django 5.1.7 on 2025-03-10 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='section1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(max_length=50)),
                ('t1h1', models.CharField(max_length=50)),
                ('t1sh1', models.CharField(max_length=50)),
                ('t1h2', models.CharField(max_length=50)),
                ('t1sh2', models.CharField(max_length=50)),
                ('t1h3', models.CharField(max_length=50)),
                ('t1sh3', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='section2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(max_length=120)),
                ('a1', models.CharField(max_length=120)),
                ('a2', models.CharField(max_length=120)),
                ('a3', models.CharField(max_length=120)),
                ('a4', models.CharField(max_length=120)),
                ('a5', models.CharField(max_length=120)),
            ],
        ),
    ]
